{% set version = "2.13.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-r.utils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.utils/R.utils_{{ version }}.tar.gz
  sha256: ab2043c34e129928ff85a037ce7a3f7791f245f49a55ee9a95bd7df0813bcf25

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r.methodss3 >=1.8.0
    - r-r.oo >=1.23.0
  run:
    - r-base
    - r-r.methodss3 >=1.8.0
    - r-r.oo >=1.23.0

test:
  commands:
    - $R -e "library('R.utils')"           # [not win]
    - "\"%R%\" -e \"library('R.utils')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.utils
  license: LGPL-2.1-or-later
  summary: Utility functions useful when programming and developing R packages.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: R.utils
# Version: 2.9.1
# Depends: R (>= 2.14.0), R.oo (>= 1.23.0)
# Imports: methods, utils, tools, R.methodsS3 (>= 1.7.1)
# Suggests: digest (>= 0.6.10)
# Title: Various Programming Utilities
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: Utility functions useful when programming and developing R packages.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/R.utils
# BugReports: https://github.com/HenrikBengtsson/R.utils/issues
# NeedsCompilation: no
# Packaged: 2019-12-05 16:48:18 UTC; hb
# Repository: CRAN
# Date/Publication: 2019-12-05 19:40:06 UTC
