{% set version = "2.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.utils
  version: {{ version|replace("-", "_") }}

source:
  fn: R.utils_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/R.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.utils/R.utils_{{ version }}.tar.gz
  sha256: b2aacc5a55d3ea86c41ac576d2583e446af145f4cb1103ad7b6f95b09ab09ff0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0
  run:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0

test:
  commands:
    - $R -e "library('R.utils')"           # [not win]
    - "\"%R%\" -e \"library('R.utils')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.utils
  license: LGPL (>= 2.1)
  summary: Utility functions useful when programming and developing R packages.
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
