appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: l8gTNT/84QOTRKyeX+LIbWQJzGS+Dj2o/F3aBXi8YbBIz2kh2lWOBpB4GrCNoXrIdphiKJYwlKJP+WpmwZjZYNoEvx3UAEJaQJfV0NRhCTqkhQtX3ndNRPpg9jW3Xc3PlD1KINncQrpGVMnjDjmBgdTFnuvVI8s7n4gNn/Pdo28jdJ9qPkiOp04Hjlyz+7g0FYQ4HP1jpJxxJwAkC5WmJDKBycRT6yv/YcchessHvkP7F6OGrtNEOh0JCOUVJYTWLNqbaTaU9Qbu96Uon42BLlbrHZ0gFJySYU39fIu3VJzKZ6nbpPQFvWDqZTKQz01577lKnt/PZFVjuciju0JbTFoA4vFtpfuYRuxm01csiUfcB0gXDZb47+GRiJWNeGe0UTnWOGI7J4dJi5Drx+rF01plgiHrsofnmjJJtiBS97HIgVtuxvVspVsQe+VtY1Qq3tVmiAEwiAHoibfxFHLvWhfWumGix/Vg3ep0mfVRTO03fIe8BcovgWe1sAeR/cXKhntSC/2HiEA30C1gvKurAlZfWEvUSQ7St5Efb8WC3VWtOZSoMosAjUAhqoTjZZA70XFEsRFxcFda13cXTOrKuhoALyQdyU7HtaRd13WffbJO3Yoi3bZXDmPeLm6VD0cnGDJwYS+yDIcuBAkxo9gmHAOd+0/ZcsIMl4L62i6Gm6I=
conda_forge_output_validation: true
